/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_grandle;
import java.io.*;


public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public int ValAbs(int nro){
        try {
            int val_ret = nro;
            if (nro < 0) 
                val_ret = nro * -1;

            return val_ret;    
        } catch (Exception e) {
            
            return -1;
        }
    }

    public int Sumar_vtas(String archivo){
        
        try {
            int total_vtas=0;
            
            BufferedReader dat_vtas = new BufferedReader(new FileReader(archivo));
            String linea = dat_vtas.readLine();

            if(linea==null)
                total_vtas = -1;
            else{
                while(linea !=null){
                    total_vtas+=Integer.parseInt(linea);
                    linea = dat_vtas.readLine();
                }
            }
            dat_vtas.close();
            return total_vtas;
            
        } 

        catch (Exception e) {
            // TODO: handle exception
            return 0;
        }
    }

    public int[] Cargar_ventas(String archivo){

        int[] arr_vtas = new int[4];

        try {
            
            byte ind = 0;
            
            BufferedReader dat_vtas = new BufferedReader(new FileReader(archivo));
            String linea = dat_vtas.readLine();

            while(linea !=null){
                arr_vtas[ind] = Integer.parseInt(linea);
                ind++;
                linea = dat_vtas.readLine();
            }

            dat_vtas.close();
            return arr_vtas;
        } 
        
        catch (Exception e) {
            // TODO: handle exception
            return arr_vtas;    
        }

    }


    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        //System.out.println("El total de ventas fue: " + new App().Sumar_vtas("app\\src\\main\\resources\\vtas.txt"));
        //System.out.println("El total de ventas fue: " + new App().Sumar_vtas("app\\src\\main\\resources\\arc_vacio.txt"));
        
        int[] arr = new App().Cargar_ventas("app\\src\\main\\resources\\vtas.txt");
        for (byte i = 0; i<arr.length; i++){
            System.out.println(arr[i] +"\t");
        }
    }
}
